### PR TITLE
Intent connected to previous block in Botmock not working and showing in dialogflow

### LINKED ISSUE #575: Bug: Sometimes the exporter duplicates the parameters and swaps the entities
**Problem**
If multiple variables are used in the training phrase of intent, and the position of both variables are in a different order in different phrases, then the exporter duplicates the parameters and swaps the entities

Screenshot 2021-03-31 at 8 52 26 PM

### LINKED ISSUE #576: Intent connected to previous block in Botmock not working and showing in dialogflow
**Problem**
Intents connected to the previous block in Botmock not working and showing in dialogflow

Screenshot 2021-03-31 at 8 57 07 PM

### PR DESCRIPTION
**Pull request by rahulchauhan049**
Fix #575 
Fix #576 

**Problem 1**
Intents connected to the previous block in Botmock not working and showing in dialogflow

Screenshot 2021-03-31 at 8 57 07 PM

**Problem**
If multiple variables are used in the training phrase of intent, and the position of both variables are in a different order in different phrases, then the exporter duplicates the parameters and swaps the entities

Screenshot 2021-03-31 at 8 52 26 PM

### CODE REVIEW

File: packages/export/src/dialogflow/index.ts [hunk 1]
```diff
@@ -857,17 +854,19 @@ export class DialogflowExporter extends BaseExporter {
       let eachLocaleUtterances = intent.utterances[locale].map(utterance => {
         const replacedText = this.#replaceVariableCharacterInText(utterance.text);
         const data : Utterance = [];
-
+        let indexOfVariableInUtterance = 0
```
Comment (Gauhar) [inline packages/export/src/dialogflow/index.ts:857]: Where is this changing? This will always be 0. Can you elaborate on this?

**Review by Gauhar — APPROVED** [review]
