### PR TITLE
Fix issue of training phrase in language other than en not working

### LINKED ISSUE #555: Training phrases are only working in english language

### PR DESCRIPTION
**Pull request by rahulchauhan049**
Fix #555 

**Problem**
Wherever the user creates a project in any language other than English, the intent training phrase of that language didn't populate in dialogflow. 

**Solution**
The issue was that we are only creating training phrases for the English language. It was hardcoded. Now we are looping over each locale and creating separate intent training phrases for each intent. 

Also if the same intent have a training phrase in a different language, then each language option in dialogflow will show a training phrase made for that specific language 

**Training Phrase for single language**

Screenshot 2021-03-12 at 1 25 07 AM

After exporting
Screenshot 2021-03-12 at 1 25 39 AM

**FOR MULTIPLE LANGUAGE PROJECT**
Screenshot 2021-03-12 at 1 27 07 AM
Screenshot 2021-03-12 at 1 27 18 AM

After exporting

Screenshot 2021-03-12 at 1 29 45 AM
Screenshot 2021-03-12 at 1 29 53 AM

### CODE REVIEW

File: packages/export/src/dialogflow/index.ts [hunk 1]
```diff
@@ -844,64 +844,65 @@ export class DialogflowExporter extends BaseExporter {
...
+    let locales = Object.keys(intent.utterances)
+    let utteranceObj = {};
+    locales.map(locale => {
+      let eachLocaleUtterances = intent.utterances[locale].map(utterance => {
+        type Utterance = {
+          text: string,
+          userDefined: boolean;
+          alias?: string,
+          meta?: string
+        }[];
```
Comment (obaid) [inline packages/export/src/dialogflow/index.ts:856]: we should define the type outside the loop

**Review by obaid — CHANGES_REQUESTED** [review]

**Review by obaid — APPROVED** [review]
